version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install --quiet --yes libboost-dev libboost-program-options-dev libboost-test-dev
      - run:
          command: make
      - run:
          command: make test
